# common configuration for ALL branches
image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y
test: off
assembly_info:
  patch: false
nuget:
  disable_publish_on_pr: true
environment:
  apiKey:
    secure: lrwREUV4nO99AU0A6xVx/MNF0BaJc8A1B8dwEGMLqmYKGqD5E7PJ/IC9RHcle6pk
before_build:
  - ps: gitversion /l console /output buildserver
  - nuget setapikey %apiKey% -Verbosity quiet
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

for:
-
  branches:
    only:
      - master
  environment:
    BUILD_TARGET: Package
  build_script:
    - cmd: if "%APPVEYOR_REPO_TAG%" == "true" set BUILD_TARGET=Deploy
    - cmd: build.bat /t:CoverageUpload;%BUILD_TARGET% /v:m

# all other branches
-
  build_script:
    - cmd: build.bat /t:CoverageUpload;Package /v:m
