name: build

on:
  push:
    branches: [main]
    tags: # match semver: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0" # Use all history for gitversion, cf.: https://github.com/actions/checkout/issues/113

      - uses: actions/setup-java@v2 # Setup Java 11 for Sonar
        with:
          distribution: "adopt"
          java-version: "11"

      - run: .\build.ps1 CiBuild
        env:
          SONAR_LOGIN: "${{ secrets.SONAR_LOGIN }}"
          NUGET_API_KEY: "${{ secrets.NUGET_API_KEY }}"
          # Use Java 1 for Sonar Scanner, Pre-installed on windows-latest
          # cf.: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#java
          #JAVA_HOME: "${{ env.JAVA_HOME_11_X64 }}"
